InventoryManagerWebsite/Models/PurchaseOrder/AddPurchaseOrderViewModel.cs
using InventoryManagerWebsite.Models.Invoice;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagerWebsite.Models.PurchaseOrder
{
    public class AddPurchaseOrderViewModel
    {
        public int InvoiceId { get; set;
        }
        public short SelectedSupplierId { get; set; }

        public ICollection<SupplierModel> Suppliers { get; set; }

        public SelectList SuppliersList => new SelectList(Suppliers, "Id", "Name");

        public int SelectedProductId { get; set; }

        public ICollection<ProductModel> Products { get; set; }

        public SelectList ProductList => new SelectList(Products, "Id", "Name");

        public ICollection<InvoiceProductModel> InvoiceProducts { get; set; }

        public decimal? TotalCost { get; set; }

        public short? Quantity { get; set; }
    }

    public class SupplierModel
    {
        public short Id { get; set; }
        public string Name { get; set; }
    }

    public class ProductModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

InventoryManagerWebsite/Models/PurchaseOrder/PurchaseOrderViewModel.cs
using InventoryManagerWebsite.Models.Invoice;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InventoryManagerWebsite.Models.PurchaseOrder
{
    public class PurchaseOrderViewModel
    {
        public ICollection<InvoiceModel> PurchaseOrders { get; set; }

    }

}

InventoryManagerWebsite/Controllers/PurchaseOrderController.cs
using DataAccess.DTO;
using InventoryManagerService.Interface;
using InventoryManagerWebsite.Models.Invoice;
using InventoryManagerWebsite.Models.PurchaseOrder;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace InventoryManagerWebsite.Controllers
{
    public class PurchaseOrderController : Controller
    {
        private readonly IProductService productService;
        private readonly IInvoiceService invoiceService;
        private readonly ISupplierService supplierService;

        public PurchaseOrderController(IProductService productService, IInvoiceService invoiceService, ISupplierService supplierService)
        {
            this.productService = productService;
            this.invoiceService = invoiceService;
            this.supplierService = supplierService;
        }

        // GET: PurchaseOrder
        public ActionResult Index()
        {
            var purchaseOrderViewModel = new PurchaseOrderViewModel
            {
                PurchaseOrders = AutoMapper.Mapper.Map<ICollection<InvoiceModel>>(invoiceService.GetInvoices(string.Empty))
            };

            return View("View", purchaseOrderViewModel );
        }

        public ActionResult New()
        {
            var model = new AddPurchaseOrderViewModel
            {
                Suppliers = AutoMapper.Mapper.Map<List<SupplierModel>>(supplierService.GetSuppliers(1)),
                Products = AutoMapper.Mapper.Map<List<ProductModel>>(productService.GetProductItems(null)),
            };

            return View("New", model);
        }

        public ActionResult Save(AddPurchaseOrderViewModel model)
        {
            InvoiceDto invoice;
            try
            {
                invoice = invoiceService.SaveNewPurchaseOrder(model.SelectedSupplierId);
                model.InvoiceId = invoice.Id;
                foreach (var product in model.InvoiceProducts)
                {
                    try
                    {
                        invoiceService.SaveNewPurchaseOrderProduct(invoice.Id, product.ProductId, product.TotalCost, product.OrderedQuantity);
                        product.IsSynced = true;
                    }
                    catch (Exception e)
                    {
                        product.IsSynced = false;
                        product.SyncMessage = e.Message;
                    }
                }
                if (model.InvoiceProducts.Any(x => x.IsSynced == false))
                {
                    throw new ApplicationException("Unable to save Invoice.");
                }
            }
            catch (Exception e)
            {
                TempData["Toast"] = e.Message;
                TempData["ToastType"] = "Error";
                model.Suppliers = AutoMapper.Mapper.Map<List<SupplierModel>>(supplierService.GetSuppliers(1));
                model.Products = AutoMapper.Mapper.Map<List<ProductModel>>(productService.GetProductItems(null));
                return View("New", model);
            }

            TempData["ToastType"] = "Success";
            TempData["Toast"] = "Invoice Saved Successfully.";
            return Index();
        }
    }
}

InventoryManagerWebsite/Views/PurchaseOrder/New.cshtml
@model InventoryManagerWebsite.Models.PurchaseOrder.AddPurchaseOrderViewModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid" style="text-align:center">
    @using (Html.BeginForm("Save", "PurchaseOrder", FormMethod.Post))
    {
        <div class="row" style="font-size: x-large; font-weight: bold">
            <div class="col-sm-12 subtitle">
                New Purchase Order
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12" style="max-width: 75%; margin: auto; padding-bottom:15px">
                @Html.DropDownListFor(x => x.SelectedSupplierId, Model.SuppliersList, "Choose Supplier", new { @class = "form-control", style = "width: auto; display: inline", required = "required" })
            </div>
        </div>
        <div class="row" style="max-width: 75%; margin: auto; padding-bottom:15px">
            <div class="col-sm-3">
                @Html.DropDownListFor(x => x.SelectedProductId, Model.ProductList, "Choose Product", new { @class = "form-control" })
                <div class="invalid-tooltip" id="productInvalidTooltip" >
                    Missing Product!
                </div>
            </div>
            <div class="col-sm-3">
                @Html.TextBoxFor(x => x.TotalCost, null, new { @class = "form-control", placeholder = "Total Cost", @type = "number" })
                <div class="invalid-tooltip" id="costInvalidTooltip">
                    Missing Total Cost!
                </div>
            </div>
            <div class="col-sm-3">
                @Html.TextBoxFor(x => x.Quantity, null, new { @class = "form-control", placeholder = "Quantity", @type = "number" })
                <div class="invalid-tooltip" id="quantityInvalidTooltip">
                    Missing Quantity!
                </div>
            </div>
            <div class="col-sm-3">
                <button class="btn btn-success" type="button" onclick="AddItem();">Add New</button>
                <button class="btn btn-success" type="submit">Save</button>
            </div>
        </div>
        <div class="row">
            <table class="table center table-striped">
                <thead class="thead-light">
                    <tr>
                        <th scope="col" class="syncStatusCell"></th>
                        <th scope="col"></th>
                        <th scope="col">Product</th>
                        <th scope="col">Total Cost</th>
                        <th scope="col">Quantity</th>
                    </tr>
                </thead>
                <tbody id="ItemsGridBody">
                    @if (Model.InvoiceProducts != null && Model.InvoiceProducts.Any())
                    {
                        for (var i = 0; i < Model.InvoiceProducts.Count(); i++)
                        {
                        <tr class="dynamicRow">
                            @{ string syncColor = Model.InvoiceProducts.ElementAt(i).IsSynced.HasValue ? @Model.InvoiceProducts.ElementAt(i).IsSynced.GetValueOrDefault(true) ? "saved" : "error" : "";}
                            <td class="syncStatusCell @syncColor" title="@Model.InvoiceProducts.ElementAt(i).SyncMessage">&nbsp;</td>
                            <td class="dynamicCell gridActionCell">
                                <img style="height:20px" class="editIcon" src="~/Content/images/edit.png" onclick="editItem(this)" />
                                <img style="height:20px" class="doneIcon hiddenIcon" src="~/Content/images/checkmark.png" onclick="completeItem(this)" />
                                <img style="height:20px" class="deleteIcon hiddenIcon" src="~/Content/images/delete.png" onclick="deleteItem(this)" />
                            </td>
                            <td class="dynamicCell">
                                <label>@Model.InvoiceProducts.ElementAt(i).Name</label>
                                <input type="hidden" name="InvoiceProducts[@i].Name" value="@Model.InvoiceProducts.ElementAt(i).Name" />
                                <input type="hidden" name="InvoiceProducts[@i].ProductId" value="@Model.InvoiceProducts.ElementAt(i).ProductId" />
                            </td>
                            <td class="dynamicCell">
                                <label>$@Model.InvoiceProducts.ElementAt(i).TotalCost.ToString("0.00")</label>
                                <input type="hidden" name="InvoiceProducts[@i].TotalCost" value="@Model.InvoiceProducts.ElementAt(i).TotalCost" />
                            </td>
                            <td class="dynamicCell">
                                <label>@Model.InvoiceProducts.ElementAt(i).OrderedQuantity</label>
                                <input type="hidden" name="InvoiceProducts[@i].OrderedQuantity" value="@Model.InvoiceProducts.ElementAt(i).OrderedQuantity" />
                            </td>
                        </tr>
                        }
                    }
                    </tbody>
            </table>
        </div>
    }
</div>

@section Scripts
{
    <script src="~/Scripts/PurchaseOrder/new.js?v=1"></script>
}

InventoryManagerWebsite/Views/PurchaseOrder/View.cshtml
@model InventoryManagerWebsite.Models.PurchaseOrder.PurchaseOrderViewModel

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid" style="text-align:center">
    <div class="row" style="font-size: x-large; font-weight: bold">
        <div class="col-sm-12 subtitle">
            Purchase Orders
        </div>
    </div>
    <div class="row" style="font-size: x-large; font-weight: bold">
        <div class="col-sm-12" style="max-width: 75%; margin: auto; padding-bottom:15px">
            <div style="text-align: right">
                @using (@Html.BeginForm("New", "PurchaseOrder", FormMethod.Get))
                {
                    <button class="btn btn-success" type="submit" style="text-align:right">Create New</button>
                }
                
            </div>
        </div>
    </div>
    @using (Html.BeginForm("View", "PurchaseOrder", FormMethod.Post))
    {
        <div class="row">
            <div class="col-sm-12">
                <table class="table center table-striped">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Invoice ID</th>
                            <th scope="col">Creation Date</th>
                            <th scope="col">Total Items</th>
                            <th scope="col">Status</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (var i = 0; i < Model.PurchaseOrders.Count(); i++)
                        {
                            string invoiceHeader = "#item" + i;
                            string invoiceDetail = "item" + i;
                        <tr>
                            <td>
                                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="@invoiceHeader">
                                    +
                                </button>
                            </td>
                            <td>
                                @Model.PurchaseOrders.ElementAt(i).Id
                                <input type="hidden" name="PurchaseOrders[@i].Id" value="@Model.PurchaseOrders.ElementAt(i).Id" />
                            </td>
                            <td>
                                @Model.PurchaseOrders.ElementAt(i).CreationDate.ToShortDateString()
                                <input type="hidden" name="PurchaseOrders[@i].CreationDate" value="@Model.PurchaseOrders.ElementAt(i).CreationDate" />
                            </td>
                            <td>
                                @Model.PurchaseOrders.ElementAt(i).TotalItems
                                <input type="hidden" name="PurchaseOrders[@i].TotalItems" value="@Model.PurchaseOrders.ElementAt(i).TotalItems" />
                            </td>
                            <td>
                                @Model.PurchaseOrders.ElementAt(i).Status
                                <input type="hidden" name="PurchaseOrders[@i].Status" value="@Model.PurchaseOrders.ElementAt(i).Status" />
                            </td>
                            <td>
                                @Html.ActionLink("Receive", "Invoice", "Transfer", new { invoiceId = Model.PurchaseOrders.ElementAt(i).Id }, new { @class = "btn btn-success"})
                            </td>
                        </tr>
                            <tr>
                                <td colspan="5" style="padding:0px">
                                    <div class="collapse" id="@invoiceDetail" style="padding:10px">
                                        <table style="width:100%">
                                            <thead>
                                                <tr>
                                                    <th scope="col">Product Name</th>
                                                    <th scope="col">Ordered</th>
                                                    <th scope="col">Received</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @for (var j = 0; j < Model.PurchaseOrders.ElementAt(i).InvoiceProducts.Count(); j++)
                                                {
                                                    <tr>
                                                        <td>
                                                            @Model.PurchaseOrders.ElementAt(i).InvoiceProducts.ElementAt(j).Name
                                                            <input type="hidden" name="PurchaseOrders[@i].InvoiceProducts[@j].Name" value="@Model.PurchaseOrders.ElementAt(i).InvoiceProducts.ElementAt(j).Name" />
                                                        </td>
                                                        <td>
                                                            @Model.PurchaseOrders.ElementAt(i).InvoiceProducts.ElementAt(j).OrderedQuantity
                                                            <input type="hidden" name="PurchaseOrders[@i].InvoiceProducts[@j].OrderedQuantity" value="@Model.PurchaseOrders.ElementAt(i).InvoiceProducts.ElementAt(j).OrderedQuantity" />
                                                        </td>
                                                        <td>
                                                            @Model.PurchaseOrders.ElementAt(i).InvoiceProducts.ElementAt(j).ReceivedQuantity
                                                            <input type="hidden" name="PurchaseOrders[@i].InvoiceProducts[@j].ReceivedQuantity" value="@Model.PurchaseOrders.ElementAt(i).InvoiceProducts.ElementAt(j).ReceivedQuantity" />
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }

</div>